api:
  auth:
    registration:
      title: Registration endpoint
      detail: Endpoint for registering user
      start: User registered
    refresh:
      title: Refresh endpoint
      detail: Endpoint for refreshing expired access token
      start: See if match
    login:
      title: Login endpoint
      detail: Endpoint for login, generates access token, refresh token
      start: User logged in
