version: '3.8'
services:
  db:
    image: postgres:15
    container_name: whiskey-db
    environment:
      POSTGRES_DB: whiskeydb
      POSTGRES_USER: whiskey
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: whiskey-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/whiskeydb
      SPRING_DATASOURCE_USERNAME: whiskey
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
