version: '3.8'

services:
  app:
    image: marekvu/whiskey-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://80.211.202.159:5432/whiskeyDB
      SPRING_DATASOURCE_USERNAME: whiskey
      SPRING_DATASOURCE_PASSWORD: whiskey123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - whiskey-net

  frontend:
    build:
      context: ./Wine_FE
    ports:
      - "3000:3000"
    networks:
      - whiskey-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: whiskeyDB
      POSTGRES_USER: whiskey
      POSTGRES_PASSWORD: whiskey123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - whiskey-net

volumes:
  pgdata:

networks:
  whiskey-net:




