version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/whiskeydb
      SPRING_DATASOURCE_USERNAME: whiskey
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - whiskey-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: whiskeydb
      POSTGRES_USER: whiskey
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - whiskey-net

volumes:
  pgdata:

networks:
  whiskey-net:
